variables:
  KANIKO_VERBOSITY: warn

stages:
  - lint
  - build

.lint_dockerfile:
  stage: lint
  image:
    name: replicated/dockerfilelint:latest
    entrypoint: [""]
  tags:
    - linux
  script:
    - /dockerfilelint/bin/dockerfilelint "$BUILD_DIR/Dockerfile"

lint_2.1:
  extends: .lint_dockerfile
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/2.1"
  
lint_2.2:
  extends: .lint_dockerfile
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/2.2"

lint_3.1:
  extends: .lint_dockerfile
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/3.1"
    
.build_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - linux
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --verbosity $KANIKO_VERBOSITY --context "$BUILD_DIR" --dockerfile "$BUILD_DIR/Dockerfile" --destination "$CI_REGISTRY_IMAGE:latest"

build_2.1:
  extends: .build_docker
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/2.1"
  
build_2.2:
  extends: .build_docker
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/2.2"

build_3.1:
  extends: .build_docker
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/3.1"