variables:
  KANIKO_VERBOSITY: warn

stages:
  - lint
  - build

lint_dockerfiles:
  stage: lint
  image:
    name: replicated/dockerfilelint:latest
    entrypoint: [""]
  tags:
    - linux
  script:
    - /dockerfilelint/bin/dockerfilelint 2.1/Dockerfile
    - /dockerfilelint/bin/dockerfilelint 2.2/Dockerfile
    - /dockerfilelint/bin/dockerfilelint 3.1/Dockerfile

.build_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - linux
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - cp "$CI_PROJECT_DIR/yarn-pubkey.gpg" "$BUILD_DIR/"
    - /kaniko/executor --verbosity $KANIKO_VERBOSITY --context "$BUILD_DIR" --dockerfile "$BUILD_DIR/Dockerfile" --destination "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

build_2.1:
  extends: .build_docker
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/2.1"
    IMAGE_TAG: "2.1"
  
build_2.2:
  extends: .build_docker
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/2.2"
    IMAGE_TAG: "2.2"

build_3.1:
  extends: .build_docker
  variables:
    BUILD_DIR: "$CI_PROJECT_DIR/3.1"
    IMAGE_TAG: "3.1"
